repos:
  - repo: local
    hooks:
      - id: lint-js
        name: "lint typescript and javascript"
        entry: /usr/bin/env npx eslint
        files: '\.jsx?$|\.tsx?$'
        language: script
        description: "Checks JS/TS code according to the package's linter configuration"
  - repo: local
    hooks:
      - id: lint-config
